## yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/settings-schema.json

# Edit this file to customize the behavior of Recyclarr beyond its defaults
# For the settings file reference guide, visit the link to the wiki below:
# https://recyclarr.dev/wiki/yaml/settings-reference/

# Comments in base_url and urls are to prevent vscode from complaining
notifications:
  verbosity: normal # Options: normal, detailed, minimal
  apprise:
    mode: stateless
    # base_url: !env_var APPRISE_URL # Point to the apprise API service URL, not Gotify
    # urls:
    #   - !file /run/secrets/gotify_recyclarrURL
