---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Documentation:
  - spcrepeau Docker-Stack:
    - icon: github-light
      href: https://github.com/spcrepeau/Docker-Stack
  - agregarr:
    - icon: agregarr
      href: https://agregarr.org/
  - audiobookrequest:
    - icon: /icons/audiobookrequest.png
      href: https://markbeep.github.io/AudioBookRequest
  - audiobookshelf:
    - icon: audiobookshelf
      href: https://www.audiobookshelf.org
  - authentik:
    - icon: authentik
      href: https://docs.goauthentik.io
  - dockhand:
    - icon: /icons/dockhand.png
      href: https://dockhand.pro/manual/#
  - gotify:
    - icon: gotify
      href: https://gotify.net
  - homepage:
    - icon: homepage
      href: https://gethomepage.dev
  - kometa:
    - icon: kometa
      href: https://kometa.wiki/en/latest
  - lidarr:
    - icon: lidarr
      href: https://lidarr.audio
  - overseerr:
    - icon: overseerr
      href: https://overseerr.dev
  - pihole:
    - icon: pi-hole
      href: https://pi-hole.net
  - prowlarr:
    - icon: prowlarr
      href: https://prowlarr.com
  - radarr:
    - icon: radarr
      href: https://radarr.video
  - recyclarr:
    - icon: recyclarr
      href: https://recyclarr.dev/wiki
  - romm:
    - icon: romm
      href: https://romm.app
  - sabnzbd:
    - icon: sabnzbd
      href: https://sabnzbd.org
  - servarr:
    - icon: servarr
      href: https://wiki.servarr.com/
  - shinkro:
    - icon: shinkro
      href: https://docs.shinkro.com
  - sonarr:
    - icon: sonarr
      href: https://sonarr.tv
  - soularr:
    - icon: /icons/soularr.png
      href: https://soularr.net
  - tautulli:
    - icon: tautulli
      href: https://tautulli.com
  - trash guides:
    - icon: trash-guides
      href: https://trash-guides.info
  - theme-park:
    - icon: themepark
      href: https://docs.theme-park.dev
  - wizarr:
    - icon: wizarr
      href: https://docs.wizarr.dev

- Github:
  - agregarr:
    - icon: agregarr
      href: https://github.com/agregarr/agregarr
  - apprise:
    - icon: apprise
      href: https://github.com/caronc/apprise-api
  - audiobookrequest:
    - icon: /icons/audiobookrequest.png
      href: https://github.com/markbeep/AudioBookRequest
  - audiobookshelf:
    - icon: audiobookshelf
      href: https://github.com/advplyr/audiobookshelf
  - authentik:
    - icon: authentik
      href: https://github.com/goauthentik/authentik
  - calibre:
    - icon: calibre
      href: https://github.com/kovidgoyal/calibre
  - dockhand:
    - icon: /icons/dockhand.png
      href: https://github.com/Finsys/dockhand
  - gotify:
    - icon: gotify
      href: https://github.com/gotify/server
  - homepage:
    - icon: homepage
      href: https://github.com/gethomepage/homepage
  - kometa:
    - icon: kometa
      href: https://github.com/Kometa-Team/Kometa
  - librespeed:
    - icon: librespeed
      href: https://github.com/librespeed/speedtest
  - lidarr:
    - icon: lidarr
      href: https://github.com/Lidarr/Lidarr
  - mariadb:
    - icon: mariadb
      href: https://github.com/MariaDB/mariadb-docker
  - overseerr:
    - icon: overseerr
      href: https://github.com/sct/overseerr
  - pihole:
    - icon: pi-hole
      href: https://github.com/pi-hole/pi-hole
  - plexautolanguages:
    - icon: plex
      href: https://github.com/JourneyDocker/Plex-Auto-Languages
  - postgres:
    - icon: postgres
      href: https://hub.docker.com/layers/library/postgres/16-alpine
  - prowlarr:
    - icon: prowlarr
      href: https://github.com/Prowlarr/Prowlarr
  - quickstart:
    - icon: kometa
      href: https://github.com/Kometa-Team/Quickstart
  - radarr:
    - icon: radarr
      href: https://github.com/Radarr/Radarr
  - recyclarr:
    - icon: recyclarr
      href: https://github.com/recyclarr/recyclarr
  - romm:
    - icon: romm
      href: https://github.com/rommapp/romm
  - sabnzbd:
    - icon: sabnzbd
      href: https://github.com/sabnzbd/sabnzbd
  - shinkro:
    - icon: shinkro
      href: https://github.com/varoOP/shinkro
  - slskd:
    - icon: slskd
      href: https://github.com/slskd/slskd
  - sonarr:
    - icon: sonarr
      href: https://github.com/Sonarr/Sonarr
  - soularr:
    - icon: /icons/soularr.png
      href: https://github.com/mrusse/soularr
  - tautulli:
    - icon: tautulli
      href: https://github.com/Tautulli/Tautulli
  - theme-park:
    - icon: themepark
      href: https://github.com/themepark-dev/theme.park
  - wizarr:
    - icon: wizarr
      href: https://github.com/wizarrrr/wizarr

- LinuxServer:
  - calibre:
    - icon: calibre
      href: https://docs.linuxserver.io/images/docker-calibre
  - kometa:
    - icon: kometa
      href: https://docs.linuxserver.io/images/docker-kometa
  - librespeed:
    - icon: librespeed
      href: https://docs.linuxserver.io/images/docker-librespeed
  - lidarr:
    - icon: lidarr
      href: https://docs.linuxserver.io/images/docker-lidarr
  - mariadb:
    - icon: mariadb
      href: https://docs.linuxserver.io/images/docker-mariadb
  - overseerr:
    - icon: overseerr
      href: https://docs.linuxserver.io/images/docker-overseerr
  - prowlarr:
    - icon: prowlarr
      href: https://docs.linuxserver.io/images/docker-prowlarr
  - radarr:
    - icon: radarr
      href: https://docs.linuxserver.io/images/docker-prowlarr
  - sabnzbd:
    - icon: sabnzbd
      href: https://docs.linuxserver.io/images/docker-sabnzbd
  - socket-proxy:
    - icon: docker
      href: https://docs.linuxserver.io/images/docker-socket-proxy
  - sonarr:
    - icon: sonarr
      href: https://docs.linuxserver.io/images/docker-sonarr
  - tautulli:
    - icon: tautulli
      href: https://docs.linuxserver.io/images/docker-tautulli
