---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Bookmarks:
    - GitHub - spcrepeau - Docker-Stack:
        - abbr: GH
          href: https://github.com/spcrepeau/Docker-Stack
