---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

headerStyle: boxed
hideVersion: true
useEqualHeights: true
fullWidth: true

theme: dark
color: slate
cardBlur: xl # xs, md, etc... see https://tailwindcss.com/docs/backdrop-blur
favicon: /images/favicon.ico
background:
  image: /images/background.jpg
  opacity: 50 # 0-100

layout:
  # Tab 1, Services
  Download Group:
    style: row
    columns: 2
    tab: Services
    header: false
    Download Calendars:
      style: row
      columns: 2
      tab: Services
      header: false
    Download Applications:
      style: row
      columns: 2
      tab: Services
      header: false
  Widget Applications:
    style: row
    columns: 3
    tab: Services
    header: false
  Normal Applications:
    style: row
    columns: 6
    tab: Services
    header: false
  Service Applications:
    style: row
    columns: 6
    tab: Services
    header: false

  # Tab 2, Recently Added & Download Queues
  Recently Added:
    style: row
    columns: 5
    tab: Recently Added & Download Queues
    header: false
  Download Queues:
    tab: Recently Added & Download Queues
    header: false

  # Tab 3, Download History
  Download History:
    style: row
    columns: 2
    tab: Download History
    header: false

  # Tab 4, Bookmarks
  Documentation:
    style: row
    columns: 5
    tab: Bookmarks
    header: true
  Github:
    style: row
    columns: 5
    tab: Bookmarks
    header: true
  LinuxServer:
    style: row
    columns: 5
    tab: Bookmarks
    header: true
