---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

headerStyle: boxed
hideVersion: true
useEqualHeights: true
fullWidth: true

theme: dark
color: slate
cardBlur: xl # xs, md, etc... see https://tailwindcss.com/docs/backdrop-blur
favicon: /images/favicon.ico
background:
  image: /images/background.jpg
  opacity: 50 # 0-100

layout:
  Download Group:
    style: row
    columns: 2
    tab: Local
    header: false
    Download Calendars:
      style: row
      columns: 2
      tab: Local
      header: false
    Download Applications:
      style: row
      columns: 2
      tab: Local
      header: false
  Server Applications:
    style: row
    columns: 3
    tab: Local
    header: false
  Media Applications:
    style: row
    columns: 4
    tab: Local
    header: false
  Misc Applications:
    style: row
    columns: 5
    tab: Local
    header: false
  Service Applications:
    style: row
    columns: 6
    tab: Local
    header: false
  Bookmarks:
    style: row
    columns: 4
    tab: Local
    header: false

  Download Queues:
    tab: Download Queues
    header: false

  Public URLs:
    style: row
    columns: 5
    tab: Public
    header: false
