---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

favicon: /images/favicon.ico
headerStyle: boxed

theme: dark
color: slate
cardBlur: xl # xs, md, etc... see https://tailwindcss.com/docs/backdrop-blur
background:
  image: /images/background.jpg
  opacity: 75 # 0-100

# layout global variables
hideVersion: true
useEqualHeights: true

layout:
  Server Applications:
    style: row
    columns: 3
  Download Applications:
    style: row
    columns: 4
  Media Applications:
    style: row
    columns: 4
  Misc Applications:
    style: row
    columns: 6
  Bookmarks:
    style: row
    columns: 4
